default:
  data_source:
    use_google_sheet: false  # use true to use gsheet by default
    google_sheet_link: "https://docs.google.com/spreadsheets/d/1RJSi7Z6r_gDtmwfPhSBlH6qIFbBd-CTQsZNGT0fSoG8/edit?usp=sharing"
    local_file_path: "FGSCdb_data.csv"
  deploy:
    deploy_shinyio: false

  gauth:
    oauth_cache: ".secrets"
    oauth_email: "your-email@example.com"
  
  shinyio:
    auth: ".secrets/SECRET" # replace 'SECRET' with auth info

development:
  data_source:
    use_google_sheet: false  # For development, use local file

production:
  data_source:
    use_google_sheet: true  # For production, use google sheets link
  deploy:
    deploy_shinyio: true # for production, deploy to shinyapps.io

