# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: Deploy Ralstonia Dashboard to shinyapps.io

on:
  push:
     branches:
       - main

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libssl-dev \
            libcurl4-openssl-dev \
            libproj-dev \
            libgdal-dev \
            libudunits2-dev \
            gdal-bin \
            git \
            libabsl-dev \
            pkg-config \
            cmake \
            libfontconfig1-dev \
            libfreetype6-dev \
            libx11-dev \
            pandoc \
            libharfbuzz-dev \
            libfribidi-dev

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: renv

    # setup renv from renv.lock
      - uses: r-lib/actions/setup-renv@v2

      - name: Install rsconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}

        # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
      - name: Authorize and deploy app
        run: |
          rsconnect::setAccountInfo(
            name = "ralstoniadashboard",
            token = "${{ secrets.SHINYAPPS_TOKEN}}",
            secret = "${{ secrets.SHINYAPPS_SECRET }}"
          )
          rsconnect::deployApp(
            appDir = "${{ github.workspace }}/RalstoniaWiltDashboard",
            appName = "RalstoniaWiltDashboard",
            appPrimaryDoc = "RWdbApp.R", # need to specify since is not `app.R` or `ui.R` + `server.R`
            account = "ralstoniadashboard",
            server = "shinyapps.io",
            forceUpdate = TRUE,
          )
        shell: Rscript {0}
