name: Deploy Ralstonia Dashboard to shinyapps.io

on:
  push:
     branches:
       - main

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4

      - name: deploy
        uses: bluegenes/shinyapps-deploy-github-action@main
        with:
          # account and application name (https://<accountName>.shinyapps.io/<appName>)
          appName: RalstoniaWiltDashboard
          appDir: RalstoniaWiltDashboard
          accountName: ralstoniadashboard

          # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}

          # force update if app with same name is already deployed
          forceUpdate: true
