# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: Deploy development version of Ralstonia Dashboard to shinyapps.io

on:
  pull_request:

jobs:
  dev-deploy-shiny:
    name: Deploy development version to shinyapps.io
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libssl-dev \
            libcurl4-openssl-dev \
            libproj-dev \
            libgdal-dev \
            libudunits2-dev \
            gdal-bin \
            git \
            libabsl-dev \
            pkg-config \
            cmake

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: renv

    # renv.lock is in repo root, so restore from root
      - uses: r-lib/actions/setup-renv@v2

      - name: Install rsconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}

      - name: Authorize and deploy app
        env:
          APPNAME: RalstoniaWiltDashboard
          ACCOUNT: ${{ secrets.DEV_SHINYAPPS_USER }}
          SERVER: shinyapps.io
        run: |
          rsconnect::setAccountInfo(
            name = "${{ secrets.DEV_SHINYAPPS_USER }}",
            token = "${{ secrets.DEV_SHINYAPPS_TOKEN}}",
            secret = "${{ secrets.DEV_SHINYAPPS_SECRET }}"
          )
          rsconnect::deployApp(
            appDir = "${{ github.workspace }}/RalstoniaWiltDashboard",
            appName = "${{ env.APPNAME }}",
            account = "${{ env.ACCOUNT }}",
            server = "${{ env.SERVER }}",
          )
#            forceUpdate = TRUE
        shell: Rscript {0}
